### ISSUE TITLE
Spawn Vehicle 

### ISSUE THREAD

**Issue by M3ManuelGold** [relavis/VehiclesPlus#10]
Basically when I try to spawn the vehicle after I reboot the server does not spawn, and if I try to remove it (take it out of the garage) I get an error in the console.

this bug is strange, after I buy the vehicle and then I do / vehicle garage and select the vehicle it works, it sparks, when I restart the server and I select the vehicle with / vehicle garage it doesn't make it spawn and if I try to remove it from the garage it gives me an error.

version PRO

Paper spigot 1.12.2 
screenshot: https://prnt.sc/u4kev9

**Comment by M3ManuelGold** [comment]
Error in console when I restart the server and leave the vehicle spawned

https://prnt.sc/u4kp6u

**Comment by relavis** [comment]
Fixed with dev build
