### ISSUE TITLE
This isnt a bug (Just a question)

### ISSUE THREAD

**Issue by IEmmortal** [relavis/VehiclesPlus#13]
I am confused on how to install the resource pack.
I put the zip in the plugins folder I also tried extracting the folder and putting it in the plugins folder and it all seems to not work.
Great plugin if I knew how to get the textures to work 👍

**Comment by relavis** [comment]
Hey,

Please copy the URL from the Example resource pack and enter it under the `resource-pack=` portion of your `server.properties` file and restart the server. Then when you join the server, it will be automatically applied.
