### ISSUE TITLE
Chunk Loading Bug

### ISSUE THREAD

**Issue by KleinWunder** [relavis/VehiclesPlus#15]
**Describe the bug**
If a player spawns a vehicle and the chunk is unloaded (due to disconnect or walking away too far) the car glitches out.
You can't get into seats (its just teleporting you to the seat location but you don't get seated). If you try to despawn the car, the armorstand will stay and you will have to delete it otherwise.

**To Reproduce**
1. Spawn a car
2. Unload the chunk (reconnect or go far away)
3. Maybe reconnect

**Expected behavior**
I would expect the system to either have a "despawn_on_unload: true/false"-feature or that the car works just normal.

**Screenshots or Video Recordings**
Not available

**Server and Plugin Informations**
 - Installed plugins: WorldEdit, WorldGuard and a bunch of unrelated stuff
 - VehiclesPlus Version: 2.0.7
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.12.2 #1618]: running raftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

 - Operating System (if applicable): Linux (VPS)

**Comment by relavis** [comment]
Fixed in 2.0.9-dev2 released on Patreon, will be fixed in public Spigot release 2.0.9 soon.
