### ISSUE TITLE
Possibility to get travelling speed (for police radar)

### ISSUE THREAD

**Issue by KleinWunder** [relavis/VehiclesPlus#16]
**Is your feature request related to a problem? Please describe.**
I own a reallife roleplay server and players keep smashing through downtown (speedlimit of like 50) with 120km/h.
I want the police-faction to be able to punish those in the frame of roleplay. like a traffic ticket or so. In order to do that
a feature like radars or the possibility to get the speed would be appreciated.

**Describe the solution you'd like**
Maybe even a PlaceholderAPI extention to add like %vp_currentspeed% to get the own speed or something.
Otherwise just the possibility to get the speed through an API or something of that nature.

**Describe alternatives you've considered**
Using WorldGuard regions to check the speed but they don't get registered as entering the region when they are in a vehicle.

**Comment by XedricKaes** [comment]
If you store the last location, and the new location, you can check if they enter a area, or are moving within. From there on you can use the api to check the speed.

**Comment by aCole1** [comment]
Hi there,

I was wanting the same feature added to the plugin. However, my idea is a bit different. 

Holding an item regardless what it is with a custom name would give you (in an action bar) the player's speed. Additionally, the plugin would be able to tell you the speed of the car in front of you if you were in say a police car. Would show on an action bar.

Thanks,
Cole

**Comment by stijnb1234** [comment]
This is possible with the API. You can use the getCurrentSpeedInKm() method for this.
