### ISSUE TITLE
Vehicle textures appearing as stone blocks

### ISSUE THREAD

**Issue by realch12** [relavis/VehiclesPlus#2]
Textures are just stone blocks. Everything works fine. It's all installed correctly. 

There is no error in the server console, where it would be.

I expected vehicles with textures for the paid version.

 Paid vehicles plus
 Latest version
 Pro
  Spigot 1.15
 Win10 64 bit

Hosted with pebble host. I use Filezilla to add files to ftp.

**Comment by realch12** [comment]
Used the texture pack from old support server

**Comment by relavis** [comment]
Have you tried the new resource packs on the Spigot page? I have just updated them for each Minecraft version.
https://www.spigotmc.org/resources/vehiclesplus.70523/
Under description

**Comment by realch12** [comment]
Nope didn't know there was more will check tommrow

**Comment by relavis** [comment]
Were you able to resolve this issue?
