### ISSUE TITLE
Planes just suddenly stopped working

### ISSUE THREAD

**Issue by RPS1222** [relavis/VehiclesPlus#24]
**Describe the bug**
Everything looks fine in the config. No errors are thrown in console. We have tried an uninstall and reinstall. 

**To Reproduce**
I have no idea, it just stopped working one day and hasn't started working since then. We didn't change any of the config files or add any other plugins as far as I know, it just broke.

**Expected behavior**
The planes are supposed to work

**Screenshots or Video Recordings**
[Short video of planes exploding submitted by someone else](https://youtu.be/alikjhJQvlQ)

**Server and Plugin Informations**
 - Installed plugins: [View list on pastebin](https://pastebin.com/9c92A3jB)
 - VehiclesPlus Version:  2.0.7
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.12.2 #1618]: PaperSpigot 1.12.2 #1618
 - Operating System (if applicable): N/A

**Additional context**
-People can enter planes
-People can turn in planes
-The planes cannot otherwise move
-The planes explode after a minute or so
I do have a video of a player in one if you would like. 

You can also contact me on Discord @RPS1222#5127 for a faster response.

**Comment by relavis** [comment]
Please follow the issue format so that I can correctly diagnose the issue.

**Comment by RPS1222** [comment]
Where is that, sorry?

**Comment by relavis** [comment]
No worries - I've added the template to the top of your issue.

**Comment by RPS1222** [comment]
Updated!

**Comment by relavis** [comment]
So from that video, it looks like the plane is actually moving, but the player's seat is not moving. You can see the smoke from the plane traveling as the player moves his wasd keys and that is why it's exploding, because it's hitting a wall or something and breaking. I'll have to look into this more. Can you shoot me a friend request on Discord so I can join the server and check it out?

**Comment by relavis** [comment]
Fixed by changing `armor-stands-tick` to `true` in paper.yml
