### ISSUE TITLE
Vehicles don't appear in GUI

### ISSUE THREAD

**Issue by G-K-G** [relavis/VehiclesPlus#25]
When you open the shop or the garage (or anything that uses a GUI) nothing appears
When you do /shop or /garage and open the gui, only the iron bars of the visual appear

**To Reproduce**
1. Install the plugin via Patreon early access
2. Put it in plugins folder
3. In game, do /vehicle or /shop

**Expected behavior**
You would be able to see vehicles

**Screenshots or Video Recordings**
https://youtu.be/ti0D3MewOgw

**Server and Plugin Informations**
 - Installed plugins: uhhhh https://prnt.sc/ug8yhb
 - VehiclesPlus Version: 2.0.8
 - Pro or Lite? Pro
 - Server Platform and Version PaperMC 1.16.3 Build #194
 - Operating System (if applicable): Windows

No errors, just GUI issues

**Comment by relavis** [comment]
Fixed in 2.0.8-dev3
