### ISSUE TITLE
Make helicopter descent with CTRL instead of Space + S and make it go up with Space instead of Space + W?

### ISSUE THREAD

**Issue by Ricco022** [relavis/VehiclesPlus#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Right now Space + S are the buttons to descent in a helicopter which is not a problem but I think it would be more comfortable to make do that with CTRL instead of Space + S because right now when you descent you can't back up and descent at the same time. Same with Space + W. You can't go forward and go up at the same time. So with going up it would be easier to make that just Space.

**Describe alternatives you've considered**
Maybe make such buttons changable in the config so people can map the keys? (Idk if that's possible within plugins)

**Additional context**
I don't have any additional context.

**Comment by stijnb1234** [comment]
You can't listen to CTRL, because it's not a key for controlling vehicles.

**Comment by stijnb1234** [comment]
Closed, because it's not possible.

**Comment by BickleBuice** [comment]
> You can't listen to CTRL, because it's not a key for controlling vehicles.

Although you can’t do that, I suggest changing it to shift, and making it so for the pilot to exit the vehicle they click shift while already landing but shifting in the air just lowers the vehicle
