### ISSUE TITLE
wish context

### ISSUE THREAD

**Issue by seogwam** [relavis/VehiclesPlus#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
1.
I want to mark the current status of the vehicle on the scoreboard.
Because I always use the action bar.
2.
I'd like to build a global player vehicle.
I'm building a day's server.
We need to deploy an ownerless vehicle.
I wish we could place the vehicle on the coordinates and the world through the command.

**Comment by relavis** [comment]
Follow the issue format
