### ISSUE TITLE
add features plz

### ISSUE THREAD

**Issue by seogwam** [relavis/VehiclesPlus#32]
Is your feature request related to a problem? Please describe.
no

Describe the solution you'd like
add features

Describe alternatives you've considered

1.
I want to mark the current status of the vehicle on the scoreboard.
Because I always use the action bar.
2.
I'd like to build a global player vehicle.
I'm building a day's server.
We need to deploy an ownerless vehicle.
I wish we could place the vehicle on the coordinates and the world through the command.

Additional context

**Comment by relavis** [comment]
Please follow the issue format.

**Comment by seogwam** [comment]
I am Korean and I am not good at English.

how to follow the issue format?
