### ISSUE TITLE
Weapon Upgrades 

### ISSUE THREAD

**Issue by LegendCObra** [relavis/VehiclesPlus#35]
**Is your feature request related to a problem? Please describe.**
I am just frustrated how you have tanks and helicopter but no weapons on it 
**Describe the solution you'd like**
I feel like Tanka should get some sort of upgrade where it can shoot explosions on it and helicopter should get some sort of gun or something 
**Describe alternatives you've considered**
Or you can link it with crackshot or plus version and use those weapons
**Additional context**

**Comment by relavis** [comment]
Tanks have explosives. Put TNT in the inventory and press spacebar while driving.
