### ISSUE TITLE
Vehicle Permissions

### ISSUE THREAD

**Issue by ItsCake-GitHub** [relavis/VehiclesPlus#36]
**Is your enhancement related to a problem? Please describe.**
My server is going to have several different jobs which require different vehicles, this includes police officers, and EMTs. I'd prefer that the regular citizens don't get access to police cars and such. 

**Describe the solution you'd like**
One solution would be to have several different types of shops which can be locked via a permission. Another simpler solution would be to just make certain vehicles in the shop not purchasable to people without their corresponding permissions.

**Comment by Ricco0227** [comment]
Can't you just simply give police officers and EMTs the correct vehicles so they can always spawn them in with /vehicle garage? This way other players can't get the vehicles.

**Comment by ItsCake-GitHub** [comment]
I didn't think about that, that is a good solution. I still think this would be a good feature to add, but that's a good idea. Thanks!

**Comment by relavis** [comment]
I'll totally look into this, I love this idea

**Comment by stijnb1234** [comment]
Will be added in the next release.
