### ISSUE TITLE
Lights / Sirens

### ISSUE THREAD

**Issue by aCole1** [relavis/VehiclesPlus#37]
I was wanting to add a lights and sirens update to the plugin.

Although they would be separate to activate. For example, using left control would just activate the lights and right control would activate both lights and sirens. For the horns, it would stay space bar. This would be for like clearing intersections using the air horn on the fire truck while still using the sirens if that makes sense.

Thanks,
Cole

**Comment by stijnb1234** [comment]
This is possible if you use the API. You can create 2 models, one with a blue/red light and one with a red/blue light. If you make a timer that toggles those two models for a vehicle, you have a working siren.
