### ISSUE TITLE
Stone texture instead of a car

### ISSUE THREAD

**Issue by filipohano** [relavis/VehiclesPlus#39]
Just bought the plugin.

Tried the 2 newest versions on both 1.16.1 and 1.16.4.
I have tried both the 1.15.2-1.16.1 and the 1.16.2 resource pack. 

The shop doesn't work. 

Instead of a car, 5 stone blocks appear. one for each wheel and one in the middle for the driver's seat I'm guessing.,

I am heavily disappointed and would like to know what's going on and if I'm the one doing something wrong.

**Comment by relavis** [comment]
Please follow the issue format.
