### ISSUE TITLE
Garage/shop UIs wont open

### ISSUE THREAD

**Issue by AaronSucks** [relavis/VehiclesPlus#4]
When you attempt to do /v shop or /v garage, the UI won't open.

1. Type /v shop or /v garage in the chat

 - Installed plugins: ImageToMap, VehiclesPlus - Pro, ProtocolLib, Vault, invSee
 - VehiclesPlus Version: Pro
 - Spigot 1.16.2

Console Log:

18.08 18:31:28 [Server] Server thread/WARN java.lang.reflect.InvocationTargetException
--
523 | 18.08 18:31:28 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
524 | 18.08 18:31:28 [Server] Server thread/WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
525 | 18.08 18:31:28 [Server] Server thread/WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
526 | 18.08 18:31:28 [Server] Server thread/WARN at java.lang.reflect.Method.invoke(Method.java:498)
527 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invokeMethod(SubCommand.java:68)
528 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.SubCommand.invoke(SubCommand.java:59)
529 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.libraries.commandlibrary.objects.LibraryCommandExecutor.onCommand(LibraryCommandExecutor.java:41)
530 | 18.08 18:31:28 [Server] Server thread/WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
531 | 18.08 18:31:28 [Server] Server thread/WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
532 | 18.08 18:31:28 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:756)
533 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1697)
534 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540)
535 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
536 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
537 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
538 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
539 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144)
540 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
541 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118)
542 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941)
543 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934)
544 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127)
545 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918)
546 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850)
547 | 18.08 18:31:28 [Server] Server thread/WARN at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
548 | 18.08 18:31:28 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)
549 | 18.08 18:31:28 [Server] Server thread/WARN Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/inventory/CraftItemStack
550 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.vehicles.reflection.versions.NMSItemStack_1_12_2.setString(NMSItemStack_1_12_2.java:28)
551 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.libraries.gui.objects.types.PaginationGui.<init>(PaginationGui.java:54)
552 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand$1.<init>(VehiclesCommand.java:180)
553 | 18.08 18:31:28 [Server] Server thread/WARN at me.legofreak107.vehiclesplus.vehicles.commands.VehiclesCommand.openGarage(VehiclesCommand.java:180)
554 | 18.08 18:31:28 [Server] Server thread/WARN ... 26 more

**Comment by relavis** [comment]
Is that the full issue? It looks like some information is missing.

**Comment by G-K-G** [comment]
plz fix

**Comment by G-K-G** [comment]
plz fix it's taking forever

**Comment by relavis** [comment]
Fixed in 2.0.8-dev1

**Comment by relavis** [comment]
Closed the wrong issue, my bad
