### ISSUE TITLE
Error while entering any command

### ISSUE THREAD

**Issue by RollexGrief** [relavis/VehiclesPlus#41]
**Describe the bug**  
Error while entering any command.

**To Reproduce**  
1. Enter any commands (/vp garage  for example)

**Expected behavior**  
1.Fix it

**Server and Plugin Information**
 - Installed plugins: ArmorStandTools, Chatty, GSit, HolographicDisplays, LightAPI, LightChatBubbles*, Movecraft, PluginConstructorAPI, PlugMan, ProtocolLib, QualityArmory, rHideTags*, rRPChat, SkinsRestorer, Vault, VehiclesPlusPro, WorldEdit, XConomy* 
 - VehiclesPlus Version: 2.0.9
 - Pro
 - PaperSpigot 1.16.4 #288
 - Windows 7 ; java 8

**Additional context**  
 https://pastebin.com/Fwg06uiZ

**Comment by relavis** [comment]
Fixed in 2.0.10-dev1
