### ISSUE TITLE
ArmorStand is gone whilst driving

### ISSUE THREAD

**Issue by Collinvh** [relavis/VehiclesPlus#44]
**Describe the bug**  
Your armorstand get's deleted/moved and you can't drive anymore

**To Reproduce**  
1. Drive around, and wait

**Expected behavior**  
It to not remove

**Screenshots or Video Recordings**  
not needed

**Server and Plugin Information**  
 - Installed plugins: ArmorStandTools, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, Multiverse-Core, ProtocolLib, (My own custom plugin), Vault, VehiclesPlusPro, WorldEdit
 - VehiclesPlus Version: 2.0.9
 - Pro or Lite? Pro
 - Server Platform and Version [eg: PaperSpigot 1.12.2 #1618]: git-Paper-1618 (MC: 1.12.2)
 - Operating System (if applicable): Linux (Ubuntu)

**Additional context**  
[13:28:13 WARN]: Wrong location! (-14, 15) should be (-14, 16), EntityArmorStand['VPHOLDER'/212, uuid='67066bb4-1f5b-4a30-a8ac-51573a5e7e83', l='MotorLand_Aragon', x=-219.98, y=70.00, z=255.43, cx=-14, cd=15, tl=1215, v=true, d=false]

**Comment by stijnb1234** [comment]
This issue still exists on 1.12.2 Not tested on 1.13 or above.

**Comment by relavis** [comment]
Fixed in 2.1.0
