### ISSUE TITLE
Lunar Client bug

### ISSUE THREAD

**Issue by SovietNina** [relavis/VehiclesPlus#47]
**Describe the bug**  

**To Reproduce**  

**Expected behavior**  

**Screenshots or Video Recordings**  
If applicable, add screenshots or video recordings to help explain your problem.
https://media.discordapp.net/attachments/786873913216335883/787996527543975946/dsadassadad.PNG?
width=960&height=178
**Server and Plugin Information**  
 - Installed plugins:
https://i.imgur.com/BlOFesB.png
 - VehiclesPlus Version:
 - Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.12.2 #1618]:
 - Operating System (if applicable):https://discordapp.com/channels/@me/787992284573859840/787997241196937246

**Additional context**  
player ride car kicked server.

**Comment by stijnb1234** [comment]
Please follow our template. We will not accept this Issue until that's changed.
