### ISSUE TITLE
Cannot drive over block in 1.12.2 server

### ISSUE THREAD

**Issue by simonchow96** [relavis/VehiclesPlus#6]
**Describe the bug**
Cars cannot go up a block while both "canDriveOverSlab" and "canDriveOverBlock" are set to true.

**Expected behavior**
Cars should be able to go up a block

**Server and Plugin Informations**
 - Installed plugins: BetterChairs, BKCommonLib, BlocksHub, BungeeJoinMessages, BungeeTabListPlus, Citizens, CoreProtect, dynmap, EConomy, Essentials, EssentialsSpawn, FastAsyncWorldEdit, HeadDatabase, ImageOnMap, JDALibLoaderBukkit, Lift, LiteBans, LockettePro, LuckPerms, MinecraftTrainSimulator, NickNames, PlaceholderAPI, PlugMan, ProtocolLib, SignEdit, SignLink, SignURLs, SimpleBackup, SK-NBeeT, Skellett, SkinsRestorer, Skript, skript-yaml, Train_Carts, UltimateChat, Vault, VehiclesPlusPro, ViaVersion, WirelessRedstone, WorldEdit
 - VehiclesPlus Version: 2.0.7
 - Pro or Lite? Pro
 - Server Platform and Version [eg: **PaperSpigot** 1.12.2 #1618]: git-Spigot-642f6d2-6103339 (MC: 1.12.2)
 - Operating System (if applicable): Ubuntu 18.04.4 LTS

**Comment by relavis** [comment]
Have you tried the newest builds of VehiclesPlus?

**Comment by relavis** [comment]
Closed due to no response.
