### ISSUE TITLE
Can´t tune my car.

### ISSUE THREAD

**Issue by FruchtSaeftchen** [relavis/VehiclesPlus#9]
Hey, i can´t use the Tuning.. Here a Screen how it looks. https://imgur.com/a/gDx1AjJ

**Expected behavior**
I expected the GUI to include everything. I also expected the Audi to be there but that's not so important. But it would be nice if you could tell me how to add it.

**Screenshots or Video Recordings**
https://imgur.com/a/gDx1AjJ

**Server and Plugin Informations**
 - Installed plugins: Essentials, PermissionsEx, ProtocolLib, Vault and VehiclesPlusPro
 - VehiclesPlus Version:
 - Pro
 - Spigot 1.12.2 & a Local server for test.

There will be no mistake. I don't know if I'm doing something wrong, but when I'm in the menu, it just looks like on the screen above.

**Comment by relavis** [comment]
Fixed in 2.0.9
